#!/usr/bin/env bash
set -euo pipefail

# Generate a docker-ready .env file from the appsettings templates.
#
# Usage:
#   ./scripts/generate-env-file.sh prod [-o <output>]   From sharepassword/appsettings.json.in (default output: .env.prod)
#   ./scripts/generate-env-file.sh dev  [-o <output>]   Base template merged with appsettings.Development.json.in (default output: .env.dev)
#
# Keys are flattened to ASP.NET Core environment format (Section__Key=value,
# arrays as Section__0). Adjustments for containers:
#   - Kestrel__* is omitted (the image binds http://+:8080)
#   - SQLite path App_Data/ is rewritten to the /app/data volume
#   - ASPNETCORE_ENVIRONMENT is set from the chosen mode
#
# Fill in the secrets afterwards, then use the file as .env.docker for
# ./start-docker.sh (e.g. cp .env.prod .env.docker). Generated files are
# gitignored; never commit them once secrets are filled in.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
BASE_TEMPLATE="$REPO_ROOT/sharepassword/appsettings.json.in"
DEV_TEMPLATE="$REPO_ROOT/sharepassword/appsettings.Development.json.in"

usage() {
	sed -n '4,18p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
	exit 1
}

if ! command -v jq >/dev/null 2>&1; then
	echo "ERROR: jq is required (https://jqlang.org)." >&2
	exit 1
fi

MODE="${1:-}"
shift || true

case "$MODE" in
	prod)
		ENVIRONMENT="Production"
		OUTPUT="$REPO_ROOT/.env.prod"
		MERGED_JSON=$(jq '.' "$BASE_TEMPLATE")
		SOURCES="sharepassword/appsettings.json.in"
		;;
	dev)
		ENVIRONMENT="Development"
		OUTPUT="$REPO_ROOT/.env.dev"
		MERGED_JSON=$(jq -s '.[0] * .[1]' "$BASE_TEMPLATE" "$DEV_TEMPLATE")
		SOURCES="sharepassword/appsettings.json.in + sharepassword/appsettings.Development.json.in"
		;;
	*)
		usage
		;;
esac

while [[ $# -gt 0 ]]; do
	case "$1" in
		-o|--output)
			[[ $# -ge 2 ]] || usage
			OUTPUT="$2"
			shift 2
			;;
		*)
			usage
			;;
	esac
done

# Multi-line values cannot be represented in dotenv format (no escape
# syntax in docker compose env_file), so they are skipped; the app falls
# back to its built-in defaults, and mail templates are editable in the
# admin UI anyway.
FLATTENED=$(jq -r '
	.SqliteStorage.ConnectionString |= (if type == "string" then sub("App_Data/"; "/app/data/") else . end)
	| paths(scalars) as $p
	| select($p[0] != "Kestrel")
	| (getpath($p) | if . == null then "" else tostring end) as $v
	| select($v | contains("\n") | not)
	| "\([$p[] | tostring] | join("__"))=\($v)"
' <<<"$MERGED_JSON")

SKIPPED=$(jq -r '
	paths(scalars) as $p
	| select($p[0] != "Kestrel")
	| select(getpath($p) | tostring | contains("\n"))
	| [$p[] | tostring] | join("__")
' <<<"$MERGED_JSON")

{
	echo "# Generated by scripts/generate-env-file.sh ($MODE) on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
	echo "# Source: $SOURCES"
	echo "# Fill in secrets before use. Do not commit this file."
	echo "ASPNETCORE_ENVIRONMENT=$ENVIRONMENT"
	echo "$FLATTENED"
} > "$OUTPUT"

echo "Wrote $OUTPUT ($(grep -c '=' "$OUTPUT") variables, ASPNETCORE_ENVIRONMENT=$ENVIRONMENT)"

if [[ -n "$SKIPPED" ]]; then
	echo "Skipped multi-line values (not representable in env format; app defaults apply):"
	sed 's/^/  /' <<<"$SKIPPED"
fi

if grep -q '^AdminAuth__PasswordHash=$' "$OUTPUT"; then
	echo "NEXT: set AdminAuth__PasswordHash. Generate with:"
	echo "  dotnet run --project ./sharepassword -- hash-admin-password --password '<password>'"
fi

if grep -q 'ChangeThis' "$OUTPUT"; then
	echo "NEXT: replace placeholder values (search for 'ChangeThis'):"
	grep -n 'ChangeThis' "$OUTPUT" | cut -d= -f1 | sed 's/^/  /'
fi

if grep -q '^Application__EnableHttpsRedirection=true$' "$OUTPUT"; then
	echo "NOTE: EnableHttpsRedirection=true — the container serves plain HTTP on 8080,"
	echo "      so keep TLS at a reverse proxy or set it to false for local containers."
fi

echo "To use with start-docker.sh: cp $(basename "$OUTPUT") .env.docker"
